name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'  # Ensure Go 1.24.0 is used

    - name: Install SDL2 dependencies
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

    - name: Verify dependencies
      run: go mod tidy

    - name: Build
      run: go build -o chip8 cmd/main.go

    - name: Verify build output
      run: ls -lh chip8
